server:
  port: 8082

spring:
  datasource:
    username: rotar
    url: jdbc:postgresql://localhost:5433/mb
    driverClassName: org.postgresql.Driver
    password: erutus91
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: 'true'
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
json?key: appid=a411ffa6ae7c2bb514b30cfe1374120f&units=metric
